CREATE TABLE `pro_stock_basic` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'TS代码',
  `symbol` varchar(6) COLLATE utf8mb4_bin NOT NULL COMMENT '股票代码',
  `name` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '股票名称',
  `area` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所在地域',
  `industry` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属行业',
  `fullname` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '股票全称',
  `enname` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '英文全称',
  `market` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '市场类型 （主板/中小板/创业板）',
  `exchange` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易所代码',
  `curr_type` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易货币',
  `list_status` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '上市状态： L上市 D退市 P暂停上市',
  `list_date` date DEFAULT NULL COMMENT '上市日期',
  `delist_date` date DEFAULT NULL COMMENT '退市日期',
  `is_hs` varchar(1) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否沪深港通标的，N否 H沪股通 S深股通',
  `created_date` date DEFAULT NULL,
  `cnspell` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '拼音缩写',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10219 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='股票基础信息数据'